= Getting Started with MuleSoft MCP Server

Learn how to set up and configure MuleSoft MCP Server for your agent-ready IDE. 

[IMPORTANT] 
If you have Anypoint Code Builder, stop here. Don't perform these steps. MuleSoft MCP Server is already installed and configured in MuleSoft Dev Agent in Anypoint Code Builder. Authentication happens through the user that's logged into Anypoint Code Builder. Any permissions that the user has, MuleSoft Dev Agent will assume. For more information about MuleSoft Dev Agent, see xref:code-builder::api-ai-create-spec.adoc[].

== Before You Begin
Before you install and use MuleSoft MCP Server, make sure you meet these prerequisites.
* Anypoint Extension Pack version 1.10.0 or later +
* Git, if using MuleSoft VCS in Anypoint Code Builder +
* Node 20 or later. For more information, see link:https://nodejs.org/en/download[Download Node.js]. +
* Organization administrator access (for xref:access-management::connected-apps-overview.adoc[creating a connected app]) +
* To run the `generate_mule_flow` and `generate_api_spec` tools, enable Einstein in Access Management. For more information, see xref:access-management::enabling-einstein.adoc[].



== Set Up Authentication
Create a connected app that acts on its own behalf using the steps in xref:access-management::creating-connected-apps-dev.adoc#create-connected-app-on-its-own-behalf[Create a Connected App That Acts on Its Own Behalf].

In step 6, add these scopes. Make sure that all business groups and relevant environments are selected for these scopes.

=== Anypoint Code Builder
* Mule Developer Generative AI User

=== Anypoint Monitoring
* Monitoring Viewer

=== API Manager
* Manage APIs Configuration
* Manage Policies
* View APIs Configuration
* View Policies

=== Exchange
* Exchange Administrator
* Exchange Contributor
* Exchange Creator
* Exchange Viewer

=== General
* View Organization
* View Connected Applications

=== Runtime Manager
* Read Applications
* Create Applications
* Read Runtime Fabrics
* Cloudhub Network Viewer

=== Usage
* Usage Viewer

== Install MuleSoft MCP Server
To install the server with node, run: 
`npm install -g @mulesoft/mcp-server`

== Configure MuleSoft MCP Server
You can configure Claude Desktop, Cursor, Windsurf, Zed, and other IDEs to work with the MuleSoft MCP Server.

=== https://claude.ai/download[Claude Desktop]
Add this snippet to `claude_desktop_config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

=== https://cline.bot/[Cline]
Add this snippet to Cline `config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

=== https://www.cursor.com/[Cursor]
Add this snippet to Cursor `mcp.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

=== https://trae.ai/[Trae]
Add this snippet to Trae `mcp_settings.json` or `.vscode/mcp.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

=== https://code.visualstudio.com/[VS Code]
Add this snippet to VS Code `settings.json` or `.vscode/mcp.json` where (optional) `ANYPOINT_REGION` is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcp": {
    "servers": {
      "mulesoft": {
        "command": "npx",
        "args": ["-y", "@mulesoft/mcp-server", "start"],
        "env": {
          "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
          "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
          "ANYPOINT_REGION": "<REGION_NAME>"
        }
      }
    }
  }
}
----

=== https://www.windsurf.com/[Windsurf]
Add this snippet to Windsurf `mcp_config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

=== https://github.com/zed-industries/zed[Zed]
Add this snippet to Zed `settings.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "context_servers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

== See Also

* xref:using-mulesoft-mcp-server.adoc[]


