= Getting Started with MuleSoft MCP Server

MuleSoft MCP Server enables AI-powered development assistants in your IDE to interact with Anypoint Platform, helping you manage APIs, applications, and platform resources directly from your coding environment. Learn how to set up and configure MuleSoft MCP Server for your IDE. 

[IMPORTANT] 
====
If you have Anypoint Code Builder or Connector Builder, MuleSoft MCP Server is already installed and configured in MuleSoft Dev Agent. For more information, see xref:anypoint-code-builder::api-ai-create-spec.adoc[] and xref:connector-builder::index.adoc[].
====

== Before You Begin
Before you install and use MuleSoft MCP Server, ensure you have installed the following software:

* Anypoint Extension Pack version 1.10.0 or later
* Git
* Node.js 20 or later. Download https://nodejs.org/en/download[Node.js].

You also need permissions or access to perform these tasks:

* Organization admistrator access: xref:access-management::connected-apps-overview.adoc[create a connected app]
* xref:access-management::enabling-einstein.adoc[Agentforce] access: run the `generate_mule_flow` and `generate_api_spec` tools .


== Set Up Authentication
Create a connected app that acts on its own behalf using the steps in xref:access-management::creating-connected-apps-dev.adoc#create-connected-app-on-its-own-behalf[Create a Connected App That Acts on Its Own Behalf].

In step 6, add these scopes. Make sure that all business groups and relevant environments are selected for these scopes.

=== Anypoint Code Builder Scopes
[cols="1,2"]
|===
|Scope|Description

|Mule Developer Generative AI User|Use natural language prompts to develop and generate flows using Agentforce for Anypoint Code Builder Generative Flows.
|===

=== Anypoint Monitoring Scopes
[cols="1,2"]
|===
|Scope|Description

|Monitoring Viewer|View but not modify content in Anypoint Monitoring.
|===

=== API Manager Scopes
[cols="1,2"]
|===
|Scope|Description

|Manage APIs Configuration|View and modify API configurations in the specified environment.

|Manage Policies|View, create, modify, and delete API policies in the specified environment.

|View APIs Configuration|View API configurations in the specified environment.

|View Policies|View API policies in the specified environment.
|===

=== Exchange Scopes
[cols="1,2"]
|===
|Scope|Description

|Exchange Administrator a|

* View, create, and download assets within a business group.
* Edit asset portal content in an existing asset version.

|Exchange Contributor|View, create, and download assets within a business group. Users with this permission can edit asset portal content in an existing asset version.

|Exchange Creator|Create new assets within a business group’s catalog.

|Exchange Viewer|View and download assets within a business group.
|===

=== General Scopes
[cols="1,2"]
|===
|Scope|Description

|View Organization|View organization information.

|View Connected Applications|View connected applications.
|===

=== Runtime Manager Scopes
[cols="1,2"]
|===
|Scope|Description

|Read Applications|View applications in a specific environment.

|Create Applications|Create applications in a specific environment.

|Read Runtime Fabrics|Query Runtime Fabric instances in the organization.

|Cloudhub Network Viewer|View CloudHub and CloudHub 2.0 network resources.
|===

=== Usage Scopes
[cols="1,2"]
|===
|Scope|Description

|Usage Viewer|View usage reports.
|===

== Install MuleSoft MCP Server

To install the server with Node.js, run: 
`npm install -g @mulesoft/mcp-server`

== Configure MuleSoft MCP Server
You can configure Claude Desktop, Cursor, Windsurf, Zed, and other IDEs to work with the MuleSoft MCP Server.

For more information about Anypoint Platform regional services, see xref:hosting-home::index.adoc#control-plane-hosting-options[].

=== Claude Desktop
Add this snippet to `claude_desktop_config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://claude.ai/download[Claude Desktop].

=== Cline
Add this snippet to Cline `config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://cline.bot/[Cline].

=== Cursor
Add this snippet to Cursor `mcp.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://www.cursor.com/[Cursor].

=== Trae
Add this snippet to Trae `mcp_settings.json` or `.vscode/mcp.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://trae.ai/[Trae].

=== VS Code
Add this snippet to VS Code `settings.json` or `.vscode/mcp.json` where (optional) `ANYPOINT_REGION` is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcp": {
    "servers": {
      "mulesoft": {
        "command": "npx",
        "args": ["-y", "@mulesoft/mcp-server", "start"],
        "env": {
          "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
          "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
          "ANYPOINT_REGION": "<REGION_NAME>"
        }
      }
    }
  }
}
----

Download https://code.visualstudio.com/[VS Code].

=== Windsurf
Add this snippet to Windsurf `mcp_config.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "mcpServers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://www.windsurf.com/[Windsurf].

=== Zed
Add this snippet to Zed `settings.json` where `ANYPOINT_REGION` (optional) is one of these values: `PROD_US`, `PROD_EU`, `PROD_CA`, or `PROD_JP`.

----
{
  "context_servers": {
    "mulesoft": {
      "command": "npx",
      "args": ["-y", "@mulesoft/mcp-server", "start"],
      "env": {
        "ANYPOINT_CLIENT_ID": "<YOUR_CLIENT_ID>",
        "ANYPOINT_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>",
        "ANYPOINT_REGION": "<REGION_NAME>"
      }
    }
  }
}
----

Download https://github.com/zed-industries/zed[Zed].

== See Also

* xref:using-mulesoft-mcp-server.adoc[]
